CREATE TABLE public.brands (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone NOT NULL,
    name varchar(100) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT brands_pkey PRIMARY KEY (id),
    CONSTRAINT uniqueName UNIQUE (name)
);

CREATE TABLE public.categories (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone NOT NULL,
    description varchar(100),
    name varchar(50) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (id)
);

CREATE TABLE public.product_category (
    product_id uuid NOT NULL,
    category_id integer NOT NULL,
    CONSTRAINT product_category_pkey PRIMARY KEY (product_id, category_id)
);

CREATE TABLE public.product_property (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    value varchar(100) NOT NULL,
    product_id uuid NOT NULL,
    property_id integer NOT NULL,
    CONSTRAINT product_property_pkey PRIMARY KEY (id),
    CONSTRAINT uniqueProductProperty UNIQUE (product_id, property_id)
);

CREATE TABLE public.products (
    id uuid NOT NULL,
    barcode varchar(50),
    cost numeric(10, 2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description varchar(255),
    name varchar(100) NOT NULL,
    price numeric(10, 2) NOT NULL,
    sku varchar(50) NOT NULL,
    stock integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    brand_id integer,
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT uniquesku UNIQUE (sku),
    CONSTRAINT uniquebarcode UNIQUE (barcode)
);

CREATE TABLE public.properties (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone NOT NULL,
    name varchar(50) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT properties_pkey PRIMARY KEY (id)
);

ALTER TABLE public.product_category
    ADD CONSTRAINT fk_product FOREIGN KEY (product_id)
    REFERENCES public.products (id);

ALTER TABLE public.product_category
    ADD CONSTRAINT fk_category FOREIGN KEY (category_id)
    REFERENCES public.categories (id);

ALTER TABLE public.product_property
    ADD CONSTRAINT fk_property FOREIGN KEY (property_id)
    REFERENCES public.properties (id);

ALTER TABLE public.product_property
    ADD CONSTRAINT fk_product_property FOREIGN KEY (product_id)
    REFERENCES public.products (id);

ALTER TABLE public.products
    ADD CONSTRAINT fk_brand FOREIGN KEY (brand_id)
    REFERENCES public.brands (id);
